spring.application.name=compass-backend

spring.ai.google.genai.chat.model=gemini-3.1-flash-lite
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.dimensions=768
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
